[package]
name = "prototype-0"
version = "0.1.0"
edition = "2021"
default-run = "prototype-0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
regex-lite = "0.1.5"

[[bin]]
name = "engine"
src = "src/engine/bin.rs"

